name: rent-ease
channels:
  - conda-forge
  - defaults

dependencies:
  # Python
  - python=3.12

  # Core framework & DB
  - fastapi>=0.115.6
  - uvicorn>=0.32.1
  - alembic>=1.14.0
  - sqlalchemy>=2.0.36
  - asyncpg>=0.30.0
  - python-dotenv>=1.0.1

  # Pydantic & settings
  - pydantic>=2.5.2
  - pydantic-settings>=2.10
  - email-validator             # for the pydantic[email] extra

  # Auth / crypto
  - python-jose>=3.3.0
  - bcrypt=4.0.1
  - passlib=1.7.4
  - greenlet>=3.1.1

  # Testing & HTTP
  - pytest>=8.0.0
  - pytest-asyncio>=0.23.5
  - pytest-cov>=4.1.0
  - httpx>=0.27.0

  # Code quality / tooling
  - black>=24.1.0
  - isort>=5.13.0

  # File uploads
  - python-multipart>=0.0.20

  # Development utilities
  - honcho
  - pip

  - pip:
    - pre-commit
    - autoflake
