name: rent-ease
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - fastapi
  - honcho # procfile, multiple processes in dev env
  - uvicorn
  - sqlalchemy
  - pydantic
  - passlib[bcrypt]
  - python-jose
  - requests
  - pip
  - pip:
      - pre-commit
