"""units and leases

Revision ID: 3cdc333b3266
Revises: 62e407a50105
Create Date: 2025-07-31 19:07:42.055189

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.sql import func

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3cdc333b3266"
down_revision: Union[str, None] = "62e407a50105"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "units",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("property_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("monthly_rent", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=func.now(),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["property_id"], ["properties.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("property_id", "name", name="uq_unit_name_per_property"),
    )
    op.create_index(op.f("ix_units_id"), "units", ["id"], unique=False)
    op.create_index(
        op.f("ix_units_property_id"), "units", ["property_id"], unique=False
    )
    op.create_table(
        "leases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=func.now(),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["tenant_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["unit_id"], ["units.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "unit_id", "tenant_id", "start_date", name="uq_lease_unique"
        ),
    )
    op.create_index(op.f("ix_leases_id"), "leases", ["id"], unique=False)
    op.create_index(op.f("ix_leases_tenant_id"), "leases", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_leases_unit_id"), "leases", ["unit_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_leases_unit_id"), table_name="leases")
    op.drop_index(op.f("ix_leases_tenant_id"), table_name="leases")
    op.drop_index(op.f("ix_leases_id"), table_name="leases")
    op.drop_table("leases")
    op.drop_index(op.f("ix_units_property_id"), table_name="units")
    op.drop_index(op.f("ix_units_id"), table_name="units")
    op.drop_table("units")
    # ### end Alembic commands ###
