"""added user roles

Revision ID: 6636d8c9b16f
Revises: ef2910566747
Create Date: 2025-07-24 18:04:04.738815

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6636d8c9b16f"
down_revision: Union[str, None] = "ef2910566747"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    user_roles_enum = sa.Enum("OWNER", "ADMIN", "TENANT", name="enumuserroles")
    user_roles_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "users",
        sa.Column(
            "role",
            user_roles_enum,
            nullable=False,
            server_default="TENANT",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###
