"""change_invoice_to_file_id

Revision ID: 7a44552d02a7
Revises: f83a5b0c33e5
Create Date: 2025-09-11 21:49:19.435805

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "7a44552d02a7"
down_revision: Union[str, None] = "f83a5b0c33e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
