"""change_invoice_to_file_id

Revision ID: 7c63121eff9b
Revises: 7a44552d02a7
Create Date: 2025-09-11 21:50:50.782752

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7c63121eff9b"
down_revision: Union[str, None] = "7a44552d02a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments", sa.Column("invoice_file_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_payments_invoice_file_id"),
        "payments",
        ["invoice_file_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "payments", "files", ["invoice_file_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_column("payments", "invoice_file_url")
    op.drop_column("payments", "invoice_file_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments",
        sa.Column(
            "invoice_file_name", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "payments",
        sa.Column(
            "invoice_file_url", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "payments", type_="foreignkey")
    op.drop_index(op.f("ix_payments_invoice_file_id"), table_name="payments")
    op.drop_column("payments", "invoice_file_id")
    # ### end Alembic commands ###
