"""add_autoincrement_to_primary_keys

Revision ID: 9abe71525d5b
Revises: 68af29647dcf
Create Date: 2025-09-02 09:50:06.471793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9abe71525d5b'
down_revision: Union[str, None] = '68af29647dcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
