"""add_invoice_fields_to_payments

Revision ID: f83a5b0c33e5
Revises: 608a20260ae1
Create Date: 2025-09-11 21:46:03.256816

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f83a5b0c33e5"
down_revision: Union[str, None] = "608a20260ae1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payments", sa.Column("invoice_file_url", sa.String(), nullable=True)
    )
    op.add_column(
        "payments", sa.Column("invoice_file_name", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payments", "invoice_file_name")
    op.drop_column("payments", "invoice_file_url")
    # ### end Alembic commands ###
