services:

  postgres:
    image: postgres:14.11
    container_name: RentEaseDBcontainer
    volumes:
        - ./postgres_multiple_dbs:/docker-entrypoint-initdb.d
    environment:
        - POSTGRES_MULTIPLE_DATABASES=rentease_db_dev,rentease_db_test
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
