#!/usr/bin/env python

import sys
from honcho.manager import Manager

if __name__ == "__main__":
    manager = Manager()

    manager.add_process("client", "cd client && ENV=dev yarn dev")

    manager.add_process(
        "server",
        (
            "ENV=dev uvicorn app.main:app "
            "--reload "
            "--reload-exclude=client/* "
            "--port 8000"
        )
    )

    # Run both processes concurrently
    manager.loop()
    sys.exit(manager.returncode)

#!/usr/bin/env python

# import sys
# import os
# from honcho.manager import Manager

# if __name__ == "__main__":
#     manager = Manager()

#     # Sprawdzamy system operacyjny
#     if os.name == 'nt':  # Windows
#         client_command = "cd client && set ENV=dev && yarn dev"
#         server_command = (
#             "set ENV=dev && uvicorn app.main:app "
#             "--reload "
#             "--reload-exclude=client/* "
#             "--port 8000"
#         )
#     else:  # Unix-like system (Linux, macOS)
#         client_command = "cd client && ENV=dev yarn dev"
#         server_command = (
#             "ENV=dev uvicorn app.main:app "
#             "--reload "
#             "--reload-exclude=client/* "
#             "--port 8000"
#         )

#     # Dodajemy procesy
#     manager.add_process("client", client_command)
#     manager.add_process("server", server_command)

#     # Uruchamiamy oba procesy równocześnie
#     manager.loop()
#     sys.exit(manager.returncode)