#!/usr/bin/env python

import sys
from honcho.manager import Manager

if __name__ == "__main__":
    manager = Manager()

    manager.add_process("client", "cd client && ENV=dev yarn dev")

    manager.add_process(
        "server",
        (
            "ENV=dev uvicorn app.main:app "
            "--reload "
            "--reload-exclude=client/* "
            "--port 8000"
        )
    )

    # Run both processes concurrently
    manager.loop()
    sys.exit(manager.returncode)
